CREATE TABLE IF NOT EXISTS user(
Id INT AUTO_INCREMENET PRIMARY KEY NOT NULL,
Username VARCHAR(20) NOT NULL,
Password VARCHAR(200) NOT NULL,
Email VARCHAR(35) NOT NULL,
Age INT NOT NULL,
Is_admin BOOLEAN DEFAULT FALSE,
Is_supplier BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS product(
Id INT AUTO_INCREMENET PRIMARY KEY NOT NULL,
Description VARCHAR(50) NOT NULL,
Current_Price FLOAT NOT NULL,
CategoryId INT NOT NULL,
FOREIGN KEY (CategoryId) REFERENCES category(Id),
Is_sold BOOLEAN DEFAULT FALSE,
Last_Price FLOAT DEFAULT NULL,
bids INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS category(
Id INT AUTO_INCREMENET PRIMARY KEY NOT NULL,
Name VARCHAR (25) NOT NULL
);

CREATE TABLE IF NOT EXISTS bid(
Id INT AUTO_INCREMENET PRIMARY KEY NOT NULL,
UserId INT NOT NULL,
FOREIGN KEY (UserId) REFERENCES user(Id),
ProductId INT NOT NULL,
FOREIGN KEY (ProductId) REFERENCES product(Id)
);

CREATE TABLE IF NOT EXISTS cart(
Id INT AUTO_INCREMENET PRIMARY KEY NOT NULL,
UserId INT NOT NULL,
FOREIGN KEY (UserId) REFERENCES user(Id),
ProductId INT NOT NULL,
FOREIGN KEY (ProductId) REFERENCES product(Id)
);